default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  password: 1234321
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: project_development

test: 
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production

